spring:
  devtools:
    remote:
      secret: DEVSECRETPASSWORD633421
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: virtualwallet
      username: admin
      password: admin
      auto-index-creation: true
  kafka:
    bootstrap-servers:
      - kafka:9092

api:
  security:
    token:
      secret: walletsecret

token: # Your personal blockcypher token here
external:
  api:
    url: https://api.blockcypher.com/v1

feign:
  client:
    config:
      blockCypherWalletClient:
        connectTimeout: 5000
        readTimeout: 5000