version: "3.8"
services:
  app:
    container_name: docker-spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: docker_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=virtualwallet
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - walletdata:/tmp/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

volumes:
  walletdata:
